### PR TITLE
wip V2 support added.

### PR DESCRIPTION
**Pull request by rocketlatotzky**
Needs additional test and soem more cleanup, but seems to work.

### CODE REVIEW

**Comment by rocketlatotzky** [comment]
Let me know what you think of the approach.

**Comment by dstepe** [comment]
@rocketlatotzky I started working toward v2 support a few weeks ago, but took a different approach. I've submitted a new draft PR for discussion, #69. My first priority was test coverage of the produced JSON, which is possible using the schema files provided by the APM project. Second, I wanted to implement v2 with a minimum of changes. This is not a complete implementation, and beyond schema validation, it is not tested, but I think we can have conversations about direction.

**Comment by dstepe** [comment]
@rocketlatotzky I only intended to share the work I started in order to keep the package moving forward. I did not mean for you to close your request.

**Comment by philkra** [comment]
@rocketlatotzky , thank you very much for your contribution. I will put everything together in the next 1-2 weeks and will use parts of your code as well. I will make sure to mention you in the contributors!

**Pull request closed without merging**
